// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameContact = "contacts"

// Contact mapped from table <contacts>
type Contact struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int32     `gorm:"column:user_id" json:"user_id"`
	ContactName  string    `gorm:"column:contact_name;not null" json:"contact_name"`
	ContactEmail string    `gorm:"column:contact_email;not null" json:"contact_email"`
	Address      string    `gorm:"column:address" json:"address"`
	PhoneNumber  string    `gorm:"column:phone_number" json:"phone_number"`
	Note         string    `gorm:"column:note" json:"note"`
	CreatedAt    time.Time `gorm:"column:created_at;default:pg_systimestamp()" json:"created_at"`
	UpdateAt     time.Time `gorm:"column:update_at;default:pg_systimestamp()" json:"update_at"`
}

// TableName Contact's table name
func (*Contact) TableName() string {
	return TableNameContact
}
