// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserEmail = "user_emails"

// UserEmail mapped from table <user_emails>
type UserEmail struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmailID     int32     `gorm:"column:email_id" json:"email_id"`
	RecipientID int32     `gorm:"column:recipient_id" json:"recipient_id"`
	IsRead      bool      `gorm:"column:is_read" json:"is_read"`
	ReadAt      time.Time `gorm:"column:read_at" json:"read_at"`
	Folder      int32     `gorm:"column:folder;not null;default:1;comment:1：收件箱，2：发件箱，3：草稿，4：垃圾箱" json:"folder"` // 1：收件箱，2：发件箱，3：草稿，4：垃圾箱
}

// TableName UserEmail's table name
func (*UserEmail) TableName() string {
	return TableNameUserEmail
}
