// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	Password     string    `gorm:"column:password;not null" json:"password"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	FirstName    string    `gorm:"column:first_name" json:"first_name"`
	LastName     string    `gorm:"column:last_name" json:"last_name"`
	BirthDate    time.Time `gorm:"column:birth_date" json:"birth_date"`
	PhoneNumber  string    `gorm:"column:phone_number" json:"phone_number"`
	ProfilePhoto []uint8   `gorm:"column:profile_photo" json:"profile_photo"`
	CreatedAt    time.Time `gorm:"column:created_at;default:pg_systimestamp()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:pg_systimestamp()" json:"updated_at"`
	Gender       int32     `gorm:"column:gender;not null;default:1;comment:1：男，2：女" json:"gender"`        // 1：男，2：女
	Status       int32     `gorm:"column:status;not null;default:1;comment:1：正常用户，2：非正常用户" json:"status"` // 1：正常用户，2：非正常用户
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
