// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRelation = "user_relations"

// UserRelation mapped from table <user_relations>
type UserRelation struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserOneID     int32     `gorm:"column:user_one_id" json:"user_one_id"`
	UserTwoID     int32     `gorm:"column:user_two_id" json:"user_two_id"`
	ActionUserID  int32     `gorm:"column:action_user_id" json:"action_user_id"`
	RequestedDate time.Time `gorm:"column:requested_date;not null;default:text_date('now" json:"requested_date"`
	ResponseDate  time.Time `gorm:"column:response_date;not null;default:text_date('now" json:"response_date"`
	Status        int32     `gorm:"column:status;not null;default:1;comment:1：主动申请好友，2：被动接受好友，3：拉黑用户" json:"status"` // 1：主动申请好友，2：被动接受好友，3：拉黑用户
}

// TableName UserRelation's table name
func (*UserRelation) TableName() string {
	return TableNameUserRelation
}
